- name: solana repository
  become: true
  become_user: solana
  git:
    repo: 'https://github.com/rpcpool/solana-public.git'
    dest: /mnt/solana
    version: tags/{{ solana_version }}

- name: build solana
  become: true
  become_user: solana
  shell: source /home/solana/.cargo/env && /mnt/solana/cargo build --release
  args:
    chdir: /mnt/solana
    executable: /bin/bash

- name: yellowstone
  become: true
  become_user: solana
  git:
    repo: 'https://github.com/rpcpool/yellowstone-grpc.git'
    dest: /home/solana/yellowstone-grpc
    version: 'v1.11.1+solana.1.16.19'
