- name: solana repository
  become: true
  become_user: solana
  git:
    repo: 'https://github.com/rpcpool/solana-public.git'
    dest: /mnt/solana
    version: tags/{{ solana_version }}

- name: build solana
  become: true
  become_user: solana
  shell: source /home/solana/.cargo/env && /mnt/solana/cargo build --release
  args:
    chdir: /mnt/solana
    executable: /bin/bash

- name: yellowstone
  become: true
  become_user: solana
  git:
    repo: 'https://github.com/rpcpool/yellowstone-grpc.git'
    dest: /home/solana/yellowstone-grpc
    version: 'v1.12.0+solana.1.17.16'

# - name: jupiter
#   ansible.builtin.get_url:
#     url: https://github.com/jup-ag/jupiter-swap-api/releases/download/{{ jupiter_version }}/jupiter-swap-api-x86_64-unknown-linux-gnu.zip
#     dest: /home/solana/jupiter.zip
#     mode: '0440'
